#!/bin/bash
# Simple manual test for 10m autonomous takeoff

echo "=============================================="
echo "  minzaniX - Manual 10m Takeoff Test"
echo "=============================================="
echo ""
echo "Follow these steps:"
echo ""
echo "Step 1: Start Gazebo in Terminal 1:"
echo "  cd /Users/habibourakash/SWE/minzaniX_1.0"
echo "  export GZ_SIM_RESOURCE_PATH=\$PWD/sim_world:\$GZ_SIM_RESOURCE_PATH"
echo "  gz sim -v4 sim_world/simple_world.sdf"
echo ""
echo "  Then press PLAY button in Gazebo GUI"
echo ""
echo "Step 2: Start Flight Controller in Terminal 2:"
echo "  cd /Users/habibourakash/SWE/minzaniX_1.0/build"
echo "  ./minzanix_sim --gazebo --auto-takeoff"
echo ""
echo "The drone will:"
echo "  • Calibrate for 3 seconds"
echo "  • Arm automatically"
echo "  • Climb to 10m with 0.95 thrust"
echo "  • Hover at 10m with 0.85 thrust"
echo ""
echo "=============================================="
