/**
 * @file main.c
 * @brief STM32 Blue Pill main entry point
 * 
 * Generated by STM32CubeMX. This file initializes hardware and starts FreeRTOS.
 * The actual flight controller logic runs in tasks.c.
 */

#include "main.h"
#include "cmsis_os.h"

// Function prototypes
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_TIM1_Init(void);
static void MX_USART1_UART_Init(void);

// External task function
extern void StartControlTask(void const * argument);

int main(void)
{
    // Reset of all peripherals, Initializes the Flash interface and the Systick
    HAL_Init();
    
    // Configure the system clock
    SystemClock_Config();
    
    // Initialize all configured peripherals
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_TIM1_Init();
    MX_USART1_UART_Init();
    
    // Create FreeRTOS tasks
    osThreadDef(ControlTask, StartControlTask, osPriorityNormal, 0, 256);
    osThreadCreate(osThread(ControlTask), NULL);
    
    // Start scheduler
    osKernelStart();
    
    // Should never reach here
    while (1) {
    }
}

/**
 * @brief System Clock Configuration
 * STM32F103 @ 72MHz
 */
void SystemClock_Config(void)
{
    // TODO: Configure for 72MHz using HSE and PLL
    // This would be generated by CubeMX
}

/**
 * @brief GPIO Initialization
 */
static void MX_GPIO_Init(void)
{
    // TODO: Configure LED, arming switch, etc.
}

/**
 * @brief I2C1 Initialization (for IMU)
 */
static void MX_I2C1_Init(void)
{
    // TODO: Configure I2C for MPU6050/BMI088 IMU
}

/**
 * @brief TIM1 Initialization (for PWM outputs)
 */
static void MX_TIM1_Init(void)
{
    // TODO: Configure timer for 4-channel PWM (50Hz or DShot)
}

/**
 * @brief USART1 Initialization (for telemetry)
 */
static void MX_USART1_UART_Init(void)
{
    // TODO: Configure UART at 115200 baud
}

/**
 * @brief Error handler
 */
void Error_Handler(void)
{
    __disable_irq();
    while (1) {
    }
}
